from django.urls import path

from navigation_app import views

urlpatterns = [


    path('',views.login,name="login"),
    path('login_post',views.login_post,name="login_post"),
    path('search',views.search,name="search"),
    path('signup_post',views.signup_post,name="signup_post"),
    path('adminhome',views.adminhome,name="adminhome"),
    path('signup',views.signup,name="signup"),
    path('verifyshop',views.verifyshop,name="verifyshop"),
    path('verifyshop_search',views.verifyshop_search,name="verifyshop_search"),
    path('accept_shop/<int:id>',views.accept_shop,name="accept_shop"),
    path('reject_shop/<int:id>',views.reject_shop,name="reject_shop"),
    path('viewcompliant',views.viewcompliant,name="viewcompliant"),
    path('viewcompliant_search',views.viewcompliant_search,name="viewcompliant_search"),
    path('sendreply/<int:id>',views.sendreply,name="sendreply"),
    path('sendreply_post',views.sendreply_post,name="sendreply_post"),
    path('viewfeedback',views.viewfeedback,name="viewfeedback"),
    path('feedback_search',views.feedback_search,name="feedback_search"),
    path('viweshoprating',views.viweshoprating,name="viweshoprating"),
    path('rating_search',views.rating_search,name="rating_search"),
    path('manageroom',views.manageroom,name="manageroom"),
    path('manageroom_search',views.manageroom_search,name="manageroom_search"),
    path('addroom',views.addroom,name="addroom"),
    path('addroom_post',views.addroom_post,name="addroom_post"),
    path('manageroute',views.manageroute,name="manageroute"),
    path('addroute',views.addroute,name="addroute"),
    path('edit_route/<int:id>',views.edit_route,name="edit_route"),
    path('edit_room/<int:id>',views.edit_room,name="edit_room"),
    path('editroute_post',views.editroute_post,name="editroute_post"),
    path('delete_route/<int:id>',views.delete_route,name="delete_route"),
    path('editroom_post',views.editroom_post,name="editroom_post"),
    path('delete_room/<int:id>',views.delete_room,name="delete_room"),

    path('shophome',views.shophome,name="shophome"),
    path('manageproduct',views.manageproduct,name="manageproduct"),
    path('product_search',views.product_search,name="product_search"),
    path('addproduct',views.addproduct,name="addproduct"),
    path('addproduct_post',views.addproduct_post,name="addproduct_post"),
    path('viewrating',views.viewrating,name="viewrating"),
    path('search_rating',views.search_rating,name="search_rating"),
    path('manageoffer',views.manageoffer,name="manageoffer"),
    path('addoffer',views.addoffer,name="addoffer"),
    path('addoffers_post', views.addoffers_post, name="addoffers_post"),
    path('edit_offer/<int:id>', views.edit_offer, name="edit_offer"),
    path('editoffer_post', views.editoffer_post, name="editoffer_post"),
    path('offer_search', views.offer_search, name="offer_search"),
    path('insert_root', views.insert_root, name="insert_root"),
    path('delete_offer/<int:id>', views.delete_offer, name="delete_offer"),
    path('vieworder',views.vieworder,name="vieworder"),
    path('viewitem/<int:id>',views.viewitem,name="viewitem"),
    path('logout',views.logout,name="logout"),
    path('edit_product/<int:id>',views.edit_product,name="edit_product"),
    path('editproduct_post',views.editproduct_post,name="editproduct_post"),
    path('delete_product/<int:id>', views.delete_product, name="delete_product"),

]