# Generated by Django 3.2.23 on 2023-12-21 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation_app.user_table')),
            ],
        ),
        migrations.DeleteModel(
            name='feadback_table',
        ),
    ]
