# Generated by Django 3.2.23 on 2023-12-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation_app', '0002_auto_20231221_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='route_table',
        ),
    ]
